"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['uc.py']
DATA_FILES = ['Spaghetti.png',
 'cityTiles_043.png',
 'roads.png',
 'cityTiles_066.png',
 'roastbeef.png'
 "Spaghetti.png",
 "ad.png",
 "cityTiles_067.png",
 "bread.png",
 "cityTiles_073.png",
 "buildingTiles_041.png",
 "buildingTiles_100.png",
 "shop.png",
 "buildingTiles_113.png	",
 "buy.png",
 "soup.png",
 "carBlue2_003.png",
 "grass.png",
 "sushi.png",
 "carBlue2_009.png",
 "iceCream.png",
 "chicken.png",
 "pizza.png",
 "cityTiles_002.png",
 "potato.png",
 "waffles.png"]
OPTIONS = {'packages' : ['time','random','enum','threading', 'atexit', 'socket','pdb','pygame']}



setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
