# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

added_files = [('waffles.png', '.'),
              ('sushi.png', '.'),
              ('soup.png', '.'),
              ('Spaghetti.png', '.'),
              ('shop.png', '.'),
              ('roastbeef.png', '.'),
              ('roads.png', '.'),
              ('potato.png', '.'),
              ('pizza.png', '.'),
              ('iceCream.png', '.'),
              ('grass.png', '.'),
              ('cityTiles_073.png', '.'),
              ('cityTiles_067.png', '.'),
              ('cityTiles_066.png', '.'),
              ('cityTiles_043.png', '.'),
              ('cityTiles_002.png', '.'),
              ('chicken.png', '.'),
              ('carBlue2_009.png', '.'),
              ('carBlue2_003.png', '.'),
              ('buy.png', '.'),
              ('buildingTiles_113.png', '.'),
              ('buildingTiles_100.png', '.'),
              ('buildingTiles_041.png', '.'),
              ('bread.png', '.'),
              ('loading25%.png', '.'),
              ('loading75%.png', '.'),
              ('loading100%.png', '.'),
              ('loading50%.png', '.'),
              ('ad.png', '.')]

a = Analysis(['uc.py'],
             pathex=['/Users/williamjojarth/Documents/shopGame'],
             binaries=[],
             datas=[('waffles.png', '.'),
                           ('sushi.png', '.'),
                           ('soup.png', '.'),
                           ('Spaghetti.png', '.'),
                           ('shop.png', '.'),
                           ('roastbeef.png', '.'),
                           ('roads.png', '.'),
                           ('potato.png', '.'),
                           ('pizza.png', '.'),
                           ('iceCream.png', '.'),
                           ('grass.png', '.'),
                           ('cityTiles_073.png', '.'),
                           ('cityTiles_067.png', '.'),
                           ('cityTiles_066.png', '.'),
                           ('cityTiles_043.png', '.'),
                           ('cityTiles_002.png', '.'),
                           ('chicken.png', '.'),
                           ('carBlue2_009.png', '.'),
                           ('carBlue2_003.png', '.'),
                           ('buy.png', '.'),
                           ('buildingTiles_113.png', '.'),
                           ('buildingTiles_100.png', '.'),
                           ('buildingTiles_041.png', '.'),
                           ('loading25%.png', '.'),
                           ('loading75%.png', '.'),
                           ('loading100%.png', '.'),
                           ('loading50%.png', '.'),
                           ('bread.png', '.'),
                           ('ad.png', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='NewshopGame',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False )
